{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL | quote }}
    path: {{ .source.path | quote }}
    targetRevision: {{ .source.targetRevision | default "main" | quote }}
    {{- if .source.helm }}
    helm:
      {{- if .source.helm.valueFiles }}
      valueFiles:
        {{- range .source.helm.valueFiles }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .destination.server | quote }}
    namespace: {{ .destination.namespace | quote }}
  syncPolicy:
    {{- if .syncPolicy.automated }}
    automated:
      prune: {{ .syncPolicy.automated.prune | default true }}
      selfHeal: {{ .syncPolicy.automated.selfHeal | default true }}
    {{- end }}
---
{{- end }}
