{{- if and .Values.secret.enabled (not .Values.secret.existingName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-secret
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
