apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    app: {{ include "django-app.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "django-app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8000 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      protocol: TCP
