{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: {{ .name }}
  url: {{ .url }}
  username: {{ .username | quote }}
  password: {{ .password | quote }}
  {{- if $.Values.repoConfig }}
  insecure: {{ $.Values.repoConfig.insecure | default "false" | quote }}
  enableLfs: {{ $.Values.repoConfig.enableLfs | default "false" | quote }}
  {{- end }}
---
{{- end }}
